// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCategoriesLvl2 = "categories_lvl2"

// CategoriesLvl2 mapped from table <categories_lvl2>
type CategoriesLvl2 struct {
	Slug               string    `gorm:"column:slug;primaryKey" json:"slug"`
	Name               string    `gorm:"column:name;not null" json:"name"`
	Status             int32     `gorm:"column:status;not null" json:"status"`
	CreatedDate        time.Time `gorm:"column:created_date;not null;default:now()" json:"created_date"`
	UpdatedDate        time.Time `gorm:"column:updated_date" json:"updated_date"`
	CreatedBy          string    `gorm:"column:created_by;not null;default:'system_default'::character varying" json:"created_by"`
	UpdatedBy          string    `gorm:"column:updated_by" json:"updated_by"`
	IsVisible          bool      `gorm:"column:is_visible;not null;default:true" json:"is_visible"`
	CategoriesLvl1Slug string    `gorm:"column:categories_lvl1_slug;not null" json:"categories_lvl1_slug"`
}

// TableName CategoriesLvl2's table name
func (*CategoriesLvl2) TableName() string {
	return TableNameCategoriesLvl2
}
