// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCategoriesProduct = "categories_product"

// CategoriesProduct mapped from table <categories_product>
type CategoriesProduct struct {
	CategoriesLvl3Slug string    `gorm:"column:categories_lvl3_slug;not null" json:"categories_lvl3_slug"`
	ProductID          string    `gorm:"column:product_id;not null" json:"product_id"`
	CreatedDate        time.Time `gorm:"column:created_date;not null;default:now()" json:"created_date"`
	UpdatedDate        time.Time `gorm:"column:updated_date" json:"updated_date"`
	CreatedBy          string    `gorm:"column:created_by;not null;default:'system_default'::character varying" json:"created_by"`
	UpdatedBy          string    `gorm:"column:updated_by" json:"updated_by"`
}

// TableName CategoriesProduct's table name
func (*CategoriesProduct) TableName() string {
	return TableNameCategoriesProduct
}
