// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/noxymon/ecomm-go/domain/catalogue/pkg/dao/model"
)

func newCategoriesLvl2(db *gorm.DB, opts ...gen.DOOption) categoriesLvl2 {
	_categoriesLvl2 := categoriesLvl2{}

	_categoriesLvl2.categoriesLvl2Do.UseDB(db, opts...)
	_categoriesLvl2.categoriesLvl2Do.UseModel(&model.CategoriesLvl2{})

	tableName := _categoriesLvl2.categoriesLvl2Do.TableName()
	_categoriesLvl2.ALL = field.NewAsterisk(tableName)
	_categoriesLvl2.Slug = field.NewString(tableName, "slug")
	_categoriesLvl2.Name = field.NewString(tableName, "name")
	_categoriesLvl2.Status = field.NewInt32(tableName, "status")
	_categoriesLvl2.CreatedDate = field.NewTime(tableName, "created_date")
	_categoriesLvl2.UpdatedDate = field.NewTime(tableName, "updated_date")
	_categoriesLvl2.CreatedBy = field.NewString(tableName, "created_by")
	_categoriesLvl2.UpdatedBy = field.NewString(tableName, "updated_by")
	_categoriesLvl2.IsVisible = field.NewBool(tableName, "is_visible")
	_categoriesLvl2.CategoriesLvl1Slug = field.NewString(tableName, "categories_lvl1_slug")

	_categoriesLvl2.fillFieldMap()

	return _categoriesLvl2
}

type categoriesLvl2 struct {
	categoriesLvl2Do categoriesLvl2Do

	ALL                field.Asterisk
	Slug               field.String
	Name               field.String
	Status             field.Int32
	CreatedDate        field.Time
	UpdatedDate        field.Time
	CreatedBy          field.String
	UpdatedBy          field.String
	IsVisible          field.Bool
	CategoriesLvl1Slug field.String

	fieldMap map[string]field.Expr
}

func (c categoriesLvl2) Table(newTableName string) *categoriesLvl2 {
	c.categoriesLvl2Do.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c categoriesLvl2) As(alias string) *categoriesLvl2 {
	c.categoriesLvl2Do.DO = *(c.categoriesLvl2Do.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *categoriesLvl2) updateTableName(table string) *categoriesLvl2 {
	c.ALL = field.NewAsterisk(table)
	c.Slug = field.NewString(table, "slug")
	c.Name = field.NewString(table, "name")
	c.Status = field.NewInt32(table, "status")
	c.CreatedDate = field.NewTime(table, "created_date")
	c.UpdatedDate = field.NewTime(table, "updated_date")
	c.CreatedBy = field.NewString(table, "created_by")
	c.UpdatedBy = field.NewString(table, "updated_by")
	c.IsVisible = field.NewBool(table, "is_visible")
	c.CategoriesLvl1Slug = field.NewString(table, "categories_lvl1_slug")

	c.fillFieldMap()

	return c
}

func (c *categoriesLvl2) WithContext(ctx context.Context) *categoriesLvl2Do {
	return c.categoriesLvl2Do.WithContext(ctx)
}

func (c categoriesLvl2) TableName() string { return c.categoriesLvl2Do.TableName() }

func (c categoriesLvl2) Alias() string { return c.categoriesLvl2Do.Alias() }

func (c categoriesLvl2) Columns(cols ...field.Expr) gen.Columns {
	return c.categoriesLvl2Do.Columns(cols...)
}

func (c *categoriesLvl2) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *categoriesLvl2) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 9)
	c.fieldMap["slug"] = c.Slug
	c.fieldMap["name"] = c.Name
	c.fieldMap["status"] = c.Status
	c.fieldMap["created_date"] = c.CreatedDate
	c.fieldMap["updated_date"] = c.UpdatedDate
	c.fieldMap["created_by"] = c.CreatedBy
	c.fieldMap["updated_by"] = c.UpdatedBy
	c.fieldMap["is_visible"] = c.IsVisible
	c.fieldMap["categories_lvl1_slug"] = c.CategoriesLvl1Slug
}

func (c categoriesLvl2) clone(db *gorm.DB) categoriesLvl2 {
	c.categoriesLvl2Do.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c categoriesLvl2) replaceDB(db *gorm.DB) categoriesLvl2 {
	c.categoriesLvl2Do.ReplaceDB(db)
	return c
}

type categoriesLvl2Do struct{ gen.DO }

func (c categoriesLvl2Do) Debug() *categoriesLvl2Do {
	return c.withDO(c.DO.Debug())
}

func (c categoriesLvl2Do) WithContext(ctx context.Context) *categoriesLvl2Do {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c categoriesLvl2Do) ReadDB() *categoriesLvl2Do {
	return c.Clauses(dbresolver.Read)
}

func (c categoriesLvl2Do) WriteDB() *categoriesLvl2Do {
	return c.Clauses(dbresolver.Write)
}

func (c categoriesLvl2Do) Session(config *gorm.Session) *categoriesLvl2Do {
	return c.withDO(c.DO.Session(config))
}

func (c categoriesLvl2Do) Clauses(conds ...clause.Expression) *categoriesLvl2Do {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c categoriesLvl2Do) Returning(value interface{}, columns ...string) *categoriesLvl2Do {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c categoriesLvl2Do) Not(conds ...gen.Condition) *categoriesLvl2Do {
	return c.withDO(c.DO.Not(conds...))
}

func (c categoriesLvl2Do) Or(conds ...gen.Condition) *categoriesLvl2Do {
	return c.withDO(c.DO.Or(conds...))
}

func (c categoriesLvl2Do) Select(conds ...field.Expr) *categoriesLvl2Do {
	return c.withDO(c.DO.Select(conds...))
}

func (c categoriesLvl2Do) Where(conds ...gen.Condition) *categoriesLvl2Do {
	return c.withDO(c.DO.Where(conds...))
}

func (c categoriesLvl2Do) Order(conds ...field.Expr) *categoriesLvl2Do {
	return c.withDO(c.DO.Order(conds...))
}

func (c categoriesLvl2Do) Distinct(cols ...field.Expr) *categoriesLvl2Do {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c categoriesLvl2Do) Omit(cols ...field.Expr) *categoriesLvl2Do {
	return c.withDO(c.DO.Omit(cols...))
}

func (c categoriesLvl2Do) Join(table schema.Tabler, on ...field.Expr) *categoriesLvl2Do {
	return c.withDO(c.DO.Join(table, on...))
}

func (c categoriesLvl2Do) LeftJoin(table schema.Tabler, on ...field.Expr) *categoriesLvl2Do {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c categoriesLvl2Do) RightJoin(table schema.Tabler, on ...field.Expr) *categoriesLvl2Do {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c categoriesLvl2Do) Group(cols ...field.Expr) *categoriesLvl2Do {
	return c.withDO(c.DO.Group(cols...))
}

func (c categoriesLvl2Do) Having(conds ...gen.Condition) *categoriesLvl2Do {
	return c.withDO(c.DO.Having(conds...))
}

func (c categoriesLvl2Do) Limit(limit int) *categoriesLvl2Do {
	return c.withDO(c.DO.Limit(limit))
}

func (c categoriesLvl2Do) Offset(offset int) *categoriesLvl2Do {
	return c.withDO(c.DO.Offset(offset))
}

func (c categoriesLvl2Do) Scopes(funcs ...func(gen.Dao) gen.Dao) *categoriesLvl2Do {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c categoriesLvl2Do) Unscoped() *categoriesLvl2Do {
	return c.withDO(c.DO.Unscoped())
}

func (c categoriesLvl2Do) Create(values ...*model.CategoriesLvl2) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c categoriesLvl2Do) CreateInBatches(values []*model.CategoriesLvl2, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c categoriesLvl2Do) Save(values ...*model.CategoriesLvl2) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c categoriesLvl2Do) First() (*model.CategoriesLvl2, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CategoriesLvl2), nil
	}
}

func (c categoriesLvl2Do) Take() (*model.CategoriesLvl2, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CategoriesLvl2), nil
	}
}

func (c categoriesLvl2Do) Last() (*model.CategoriesLvl2, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CategoriesLvl2), nil
	}
}

func (c categoriesLvl2Do) Find() ([]*model.CategoriesLvl2, error) {
	result, err := c.DO.Find()
	return result.([]*model.CategoriesLvl2), err
}

func (c categoriesLvl2Do) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CategoriesLvl2, err error) {
	buf := make([]*model.CategoriesLvl2, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c categoriesLvl2Do) FindInBatches(result *[]*model.CategoriesLvl2, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c categoriesLvl2Do) Attrs(attrs ...field.AssignExpr) *categoriesLvl2Do {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c categoriesLvl2Do) Assign(attrs ...field.AssignExpr) *categoriesLvl2Do {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c categoriesLvl2Do) Joins(fields ...field.RelationField) *categoriesLvl2Do {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c categoriesLvl2Do) Preload(fields ...field.RelationField) *categoriesLvl2Do {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c categoriesLvl2Do) FirstOrInit() (*model.CategoriesLvl2, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CategoriesLvl2), nil
	}
}

func (c categoriesLvl2Do) FirstOrCreate() (*model.CategoriesLvl2, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CategoriesLvl2), nil
	}
}

func (c categoriesLvl2Do) FindByPage(offset int, limit int) (result []*model.CategoriesLvl2, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c categoriesLvl2Do) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c categoriesLvl2Do) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c categoriesLvl2Do) Delete(models ...*model.CategoriesLvl2) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *categoriesLvl2Do) withDO(do gen.Dao) *categoriesLvl2Do {
	c.DO = *do.(*gen.DO)
	return c
}
