// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/noxymon/ecomm-go/domain/catalogue/pkg/dao/model"
)

func newCategoriesLvl3(db *gorm.DB, opts ...gen.DOOption) categoriesLvl3 {
	_categoriesLvl3 := categoriesLvl3{}

	_categoriesLvl3.categoriesLvl3Do.UseDB(db, opts...)
	_categoriesLvl3.categoriesLvl3Do.UseModel(&model.CategoriesLvl3{})

	tableName := _categoriesLvl3.categoriesLvl3Do.TableName()
	_categoriesLvl3.ALL = field.NewAsterisk(tableName)
	_categoriesLvl3.Slug = field.NewString(tableName, "slug")
	_categoriesLvl3.Name = field.NewString(tableName, "name")
	_categoriesLvl3.Status = field.NewInt32(tableName, "status")
	_categoriesLvl3.CreatedDate = field.NewTime(tableName, "created_date")
	_categoriesLvl3.UpdatedDate = field.NewTime(tableName, "updated_date")
	_categoriesLvl3.CreatedBy = field.NewString(tableName, "created_by")
	_categoriesLvl3.UpdatedBy = field.NewString(tableName, "updated_by")
	_categoriesLvl3.IsVisible = field.NewBool(tableName, "is_visible")
	_categoriesLvl3.CategoriesLvl2Slug = field.NewString(tableName, "categories_lvl2_slug")

	_categoriesLvl3.fillFieldMap()

	return _categoriesLvl3
}

type categoriesLvl3 struct {
	categoriesLvl3Do categoriesLvl3Do

	ALL                field.Asterisk
	Slug               field.String
	Name               field.String
	Status             field.Int32
	CreatedDate        field.Time
	UpdatedDate        field.Time
	CreatedBy          field.String
	UpdatedBy          field.String
	IsVisible          field.Bool
	CategoriesLvl2Slug field.String

	fieldMap map[string]field.Expr
}

func (c categoriesLvl3) Table(newTableName string) *categoriesLvl3 {
	c.categoriesLvl3Do.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c categoriesLvl3) As(alias string) *categoriesLvl3 {
	c.categoriesLvl3Do.DO = *(c.categoriesLvl3Do.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *categoriesLvl3) updateTableName(table string) *categoriesLvl3 {
	c.ALL = field.NewAsterisk(table)
	c.Slug = field.NewString(table, "slug")
	c.Name = field.NewString(table, "name")
	c.Status = field.NewInt32(table, "status")
	c.CreatedDate = field.NewTime(table, "created_date")
	c.UpdatedDate = field.NewTime(table, "updated_date")
	c.CreatedBy = field.NewString(table, "created_by")
	c.UpdatedBy = field.NewString(table, "updated_by")
	c.IsVisible = field.NewBool(table, "is_visible")
	c.CategoriesLvl2Slug = field.NewString(table, "categories_lvl2_slug")

	c.fillFieldMap()

	return c
}

func (c *categoriesLvl3) WithContext(ctx context.Context) *categoriesLvl3Do {
	return c.categoriesLvl3Do.WithContext(ctx)
}

func (c categoriesLvl3) TableName() string { return c.categoriesLvl3Do.TableName() }

func (c categoriesLvl3) Alias() string { return c.categoriesLvl3Do.Alias() }

func (c categoriesLvl3) Columns(cols ...field.Expr) gen.Columns {
	return c.categoriesLvl3Do.Columns(cols...)
}

func (c *categoriesLvl3) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *categoriesLvl3) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 9)
	c.fieldMap["slug"] = c.Slug
	c.fieldMap["name"] = c.Name
	c.fieldMap["status"] = c.Status
	c.fieldMap["created_date"] = c.CreatedDate
	c.fieldMap["updated_date"] = c.UpdatedDate
	c.fieldMap["created_by"] = c.CreatedBy
	c.fieldMap["updated_by"] = c.UpdatedBy
	c.fieldMap["is_visible"] = c.IsVisible
	c.fieldMap["categories_lvl2_slug"] = c.CategoriesLvl2Slug
}

func (c categoriesLvl3) clone(db *gorm.DB) categoriesLvl3 {
	c.categoriesLvl3Do.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c categoriesLvl3) replaceDB(db *gorm.DB) categoriesLvl3 {
	c.categoriesLvl3Do.ReplaceDB(db)
	return c
}

type categoriesLvl3Do struct{ gen.DO }

func (c categoriesLvl3Do) Debug() *categoriesLvl3Do {
	return c.withDO(c.DO.Debug())
}

func (c categoriesLvl3Do) WithContext(ctx context.Context) *categoriesLvl3Do {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c categoriesLvl3Do) ReadDB() *categoriesLvl3Do {
	return c.Clauses(dbresolver.Read)
}

func (c categoriesLvl3Do) WriteDB() *categoriesLvl3Do {
	return c.Clauses(dbresolver.Write)
}

func (c categoriesLvl3Do) Session(config *gorm.Session) *categoriesLvl3Do {
	return c.withDO(c.DO.Session(config))
}

func (c categoriesLvl3Do) Clauses(conds ...clause.Expression) *categoriesLvl3Do {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c categoriesLvl3Do) Returning(value interface{}, columns ...string) *categoriesLvl3Do {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c categoriesLvl3Do) Not(conds ...gen.Condition) *categoriesLvl3Do {
	return c.withDO(c.DO.Not(conds...))
}

func (c categoriesLvl3Do) Or(conds ...gen.Condition) *categoriesLvl3Do {
	return c.withDO(c.DO.Or(conds...))
}

func (c categoriesLvl3Do) Select(conds ...field.Expr) *categoriesLvl3Do {
	return c.withDO(c.DO.Select(conds...))
}

func (c categoriesLvl3Do) Where(conds ...gen.Condition) *categoriesLvl3Do {
	return c.withDO(c.DO.Where(conds...))
}

func (c categoriesLvl3Do) Order(conds ...field.Expr) *categoriesLvl3Do {
	return c.withDO(c.DO.Order(conds...))
}

func (c categoriesLvl3Do) Distinct(cols ...field.Expr) *categoriesLvl3Do {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c categoriesLvl3Do) Omit(cols ...field.Expr) *categoriesLvl3Do {
	return c.withDO(c.DO.Omit(cols...))
}

func (c categoriesLvl3Do) Join(table schema.Tabler, on ...field.Expr) *categoriesLvl3Do {
	return c.withDO(c.DO.Join(table, on...))
}

func (c categoriesLvl3Do) LeftJoin(table schema.Tabler, on ...field.Expr) *categoriesLvl3Do {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c categoriesLvl3Do) RightJoin(table schema.Tabler, on ...field.Expr) *categoriesLvl3Do {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c categoriesLvl3Do) Group(cols ...field.Expr) *categoriesLvl3Do {
	return c.withDO(c.DO.Group(cols...))
}

func (c categoriesLvl3Do) Having(conds ...gen.Condition) *categoriesLvl3Do {
	return c.withDO(c.DO.Having(conds...))
}

func (c categoriesLvl3Do) Limit(limit int) *categoriesLvl3Do {
	return c.withDO(c.DO.Limit(limit))
}

func (c categoriesLvl3Do) Offset(offset int) *categoriesLvl3Do {
	return c.withDO(c.DO.Offset(offset))
}

func (c categoriesLvl3Do) Scopes(funcs ...func(gen.Dao) gen.Dao) *categoriesLvl3Do {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c categoriesLvl3Do) Unscoped() *categoriesLvl3Do {
	return c.withDO(c.DO.Unscoped())
}

func (c categoriesLvl3Do) Create(values ...*model.CategoriesLvl3) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c categoriesLvl3Do) CreateInBatches(values []*model.CategoriesLvl3, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c categoriesLvl3Do) Save(values ...*model.CategoriesLvl3) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c categoriesLvl3Do) First() (*model.CategoriesLvl3, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CategoriesLvl3), nil
	}
}

func (c categoriesLvl3Do) Take() (*model.CategoriesLvl3, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CategoriesLvl3), nil
	}
}

func (c categoriesLvl3Do) Last() (*model.CategoriesLvl3, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CategoriesLvl3), nil
	}
}

func (c categoriesLvl3Do) Find() ([]*model.CategoriesLvl3, error) {
	result, err := c.DO.Find()
	return result.([]*model.CategoriesLvl3), err
}

func (c categoriesLvl3Do) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CategoriesLvl3, err error) {
	buf := make([]*model.CategoriesLvl3, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c categoriesLvl3Do) FindInBatches(result *[]*model.CategoriesLvl3, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c categoriesLvl3Do) Attrs(attrs ...field.AssignExpr) *categoriesLvl3Do {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c categoriesLvl3Do) Assign(attrs ...field.AssignExpr) *categoriesLvl3Do {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c categoriesLvl3Do) Joins(fields ...field.RelationField) *categoriesLvl3Do {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c categoriesLvl3Do) Preload(fields ...field.RelationField) *categoriesLvl3Do {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c categoriesLvl3Do) FirstOrInit() (*model.CategoriesLvl3, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CategoriesLvl3), nil
	}
}

func (c categoriesLvl3Do) FirstOrCreate() (*model.CategoriesLvl3, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CategoriesLvl3), nil
	}
}

func (c categoriesLvl3Do) FindByPage(offset int, limit int) (result []*model.CategoriesLvl3, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c categoriesLvl3Do) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c categoriesLvl3Do) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c categoriesLvl3Do) Delete(models ...*model.CategoriesLvl3) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *categoriesLvl3Do) withDO(do gen.Dao) *categoriesLvl3Do {
	c.DO = *do.(*gen.DO)
	return c
}
